# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4feabb3791569313109bca131f96cfa1332a9adb865283efd4c2b352aef68a51a7dfd90c1d9d25b7af425a23e19738ff8e021e04ebb5ddce4202beb5bc6c4bfa

test:
  secret_key_base: 9e5215555e67e957bb65679a981bdd1a5e6e79fd60b094d6a24c7e61de8fc47854e88192d19f6bc663d28aa68ce2de4caa951913ee37f964afbea3dcf1e763e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
